#!/usr/bin/env bash
#
echo "ps" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	trap "echo I hate the kill comand ; rm /var/run/myscript.pid; exit" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "rm -r /var/run/myscript.pid; exit" SIGQUIT
done
